namespace HR.BrightspaceConnector
{
    /// <summary>
    /// A machine-readable format for specifying errors in HTTP API responses.
    /// </summary>
    public class ProblemDetails
    {
        /// <summary>
        /// A URI reference that identifies the problem type. 
        /// This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML). 
        /// When this member is not present, its value is assumed to be "about:blank".
        /// </summary>
        public string? Type { get; set; }

        /// <summary>
        /// A short, human-readable summary of the problem type. 
        /// It should not change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation).
        /// </summary>
        public string? Title { get; set; }

        /// <summary>
        /// The HTTP status code generated by the origin server for this occurrence of the problem.
        /// </summary>
        public int? Status { get; set; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        public string? Detail { get; set; }

        /// <summary>
        /// A URI reference that identifies the specific occurrence of the problem. 
        /// It may or may not yield further information if dereferenced.
        /// </summary>
        public string? Instance { get; set; }
    }
}
